from .proximal import generalized_doubly_stochastic_matrices_projection
from .proximal import trace_nonnegative_prox
from .proximal import primal_dual_linear_prox
from .proximal import primal_dual_trace_nonnegative_prox
from .proximal import trace_nonnegative_prox_nb
from .proximal import apply_adjoint_operator_and_override
